application: salmon-playground
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /justthesalmon
  static_files: justthesalmon.html
  upload: justthesalmon.html

- url: /post
  script: main.py
  
- url: /salmonize
  script: main.py

- url: .*
  script: main.py
  login: required
  

